# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43f09dd2edb07a991716e227ddfbd59779c7bd1ebd5403c698b2ac81792fc5f45c1f364790da75e49b45c1e0e88e9750301e6bf772408f983e44f31bdc00440c

test:
  secret_key_base: f660dc7a3060ff1e3c8afeb499367df03ab4d9f3a449df77c5a5ba1abb37bba9c022febe4874ef74300beb72a4a7e1b844d251a347bf0bc6fdaf80f4714c554e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
